site_name: Telegram-магазин
site_description: Документація платформи
site_url: https://bhy4uk.github.io/tgshop-docs/

theme:
  name: material
  language: uk
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.prune
    - navigation.top
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-night
        name: Темна тема
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Світла тема
  font:
    text: Manrope
    code: JetBrains Mono

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3

extra:
  generator: false   # прибирає "Made with Material"

extra_css:
  - styles/extra.css

nav:
  - Інструкція для власника: owner-guide.md