site_name: Telegram-магазин
site_description: Документація платформи
site_url: https://bhy4uk.github.io/insomnia.workshop/

theme:
  name: material
  language: uk
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.share
    - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Світла тема
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Темна тема
  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search

extra:
  generator: false   # прибирає "Made with Material"

extra_css:
  - styles/extra.css

nav:
  - Головна: index.md
  - Інструкція для власника: owner-guide.md